/* Generated by `npm run types` from data/schema/export-0.5.6.json. Do not edit. */

/**
 * The website's data export, schema 0.5.6. Three documents per game build: one ClassExport per class (and spec), the Manifest, and the Golden vectors. docs/export-format.md is the prose companion (ids, grades, changelog).
 */
export type BdoExport = ClassExport | Manifest | Golden;
export type Spec = "succession" | "awakening";
/**
 * A game input: Mouse0 (LMB), Mouse1 (RMB), W A S D, Shift, Space, Q E F C Z X, Tab.
 */
export type Key = string;
/**
 * How a spec lists a skill: pressable (in the skill list), reached_through (not pressable in this spec, reached from another skill), or null (not in the spec).
 */
export type SpecList = "pressable" | "reached_through" | null;
/**
 * How a value is known, in public words. game data: read from the shipped files (or a census over them). measured: observed in game. inferred: a rule consistent with the data, not read directly. needs value: not known; an editor fills it.
 */
export type PublicGrade = "game data" | "measured" | "inferred" | "needs value";
/**
 * [action, from frame, to frame]
 *
 * @minItems 3
 * @maxItems 3
 */
export type Segment = [string, number, number];
/**
 * [action, lo, hi, speed set name, ms]: the action's clock over [lo, hi) must give ms (to 0.1)
 *
 * @minItems 5
 * @maxItems 5
 */
export type GoldenClock = [string, number, number, string, number];

export interface ClassExport {
  schema: "0.5.6";
  /**
   * the game-data build stamp
   */
  build: string;
  class: string;
  spec: Spec | null;
  speeds_default: Speeds;
  provenance: {
    build: string;
    /**
     * shipped file -> what is read from it
     */
    files: {
      [k: string]: string;
    };
    /**
     * shipped file -> its content hash
     */
    sha256: {
      [k: string]: string;
    };
  };
  profile: string;
  spec_scope: {
    [k: string]: string;
  };
  skills: {
    [k: string]: Skill;
  };
  actions: {
    [k: string]: Action;
  };
  edges: {
    [k: string]: Edge;
  };
  /**
   * list id -> edge ids, shared by every row that offers the same edges
   */
  edge_lists: {
    [k: string]: string[];
  };
  /**
   * list id -> variable writes, shared by every action that makes the same ones
   */
  set_lists: {
    [k: string]: VariableSet[];
  };
  areas: {
    [k: string]: Area;
  };
  damage_lines: {
    [k: string]: DamageLine;
  };
  presets: Preset[];
  /**
   * list id -> segments, shared by follow-ups
   */
  segment_lists: {
    [k: string]: Segment[];
  };
  presets_status: string;
  /**
   * where the damage lines and hit areas were read
   */
  damage_source: string;
  counts: Counts;
  dropped: Dropped;
  /**
   * whether the presets had the skill families (skilltype.dbss) their cast-end rule needs: 'ok', 'unavailable: <reason>', or 'not generated'. export_check fails unless 'ok'.
   */
  presets_family_roots: string;
  /**
   * card id (a game skill id: the skill the presets' damage hits name, ADR 0004 item 7) -> the card
   */
  cards: {
    [k: string]: Card;
  };
  access_lists: {
    [k: string]: AccessEntry[];
  };
}
export interface Speeds {
  attack: number;
  casting: number;
  movement: number;
}
export interface Skill {
  key: string;
  ids: number[];
  name: string | null;
  type: string;
  entries: string[];
  entry_inputs: {
    keys: Key[];
    not_keys: Key[];
    text: string;
  }[];
  specs: {
    succession: SpecList;
    awakening: SpecList;
  };
  /**
   * {entry action: the action played instead on cooldown}
   */
  on_cooldown?: {
    [k: string]: string;
  };
}
export interface Action {
  clip: Clip;
  clock: Clock;
  ticks?: Tick[];
  rows: Row[];
  /**
   * key into `set_lists`: the action variable writes its frame events make
   */
  sets?: string;
  /**
   * pressed on cooldown, the game plays `action` instead
   */
  on_cooldown?: {
    action: string | null;
    skill_id: number | null;
  };
}
export interface Clip {
  anim: string | null;
  /**
   * the clip frame the action starts at
   */
  start_f: number;
  /**
   * the frame it ends at when nothing cancels it (its cut, else the clip length); null when no length is known
   */
  end_f: number | null;
  /**
   * the clip's length in frames (30 per second of animation)
   */
  frames: number | null;
}
/**
 * THE PER-ACTION CLOCK. ms for a clip span [lo, hi) at speeds S: effective frames = the span at `rate`, with each speed event replacing the rate from its frame (for remain*speed*30 frames when remain > 0, else to the end; the last event still covering a frame wins); ms = frames / 30 / (S[pool]/100) * 1000 (pool 'none': 100) plus the slow-motion excess, rounded to 0.1. Golden vectors pin it.
 */
export interface Clock {
  rate: number | null;
  pool: "attack" | "casting" | "movement" | "none";
  speed_events: number[][];
  slow_motion: boolean;
  slow_motion_events: number[][];
}
/**
 * One damage hit of an action. Its % per line is damage_lines[line].pct (null = not known).
 */
export interface Tick {
  /**
   * <action>@<frame>#<n>: n counts the action's damage ticks at the same frame
   */
  id: string;
  f: number;
  /**
   * the game skill id the hit names
   */
  skill: number;
  /**
   * damage line ids '<skill>:<line>'
   */
  lines: string[];
  /**
   * key into `areas`; null with `area_reason`
   */
  area: string | null;
  area_reason?: string;
  flight?: Flight;
  conditional?: true;
  /**
   * the hit fires when ANY of these holds
   */
  if?: {
    conditions: Condition[];
    input: string;
  }[];
}
/**
 * A projectile's flight (game data), except range (inferred). Its impact area is not in the game data.
 */
export interface Flight {
  /**
   * units per second
   */
  speed: number;
  /**
   * straight | ground-hugging | ballistic
   */
  path: string | number;
  gravity: number;
  /**
   * @minItems 3
   * @maxItems 3
   */
  launch_offset: number[];
  aim: string;
  range: number;
  reported: boolean;
}
/**
 * One non-input test of a relationship (a learned skill, a runtime state, an action variable, the class resource, the weapon stance, another test). `named` grades the NAME of the test, not whether it holds.
 */
export interface Condition {
  kind: "learned" | "not_learned" | "state" | "variable" | "class_resource" | "stance" | "test";
  text: string;
  /**
   * learned / not_learned: the game skill id
   */
  skill?: number;
  /**
   * state: the state's number
   */
  id?: number;
  name?: string;
  op?: string;
  value?: number;
  args?: number[];
  named?: PublicGrade;
}
/**
 * One selection row of an action, in engine order: the edges it offers from `from_f` (own walk rows: from the start). Within a row the FIRST passing edge is taken.
 */
export interface Row {
  /**
   * 'own' (the action's own walk) or the shared group's name
   */
  via: string;
  from_f?: number;
  /**
   * key into `edge_lists`: the row's edge ids in engine order
   */
  list: string;
}
/**
 * A RELATIONSHIP: from the action whose row lists it, to an action (and the skill it enters). continuation: the skill's own next action; exit: into another skill (or a skill press); repeat: back into the same action.
 */
export interface Edge {
  to: string;
  /**
   * graph skill key, null for a continuation inside the same skill
   */
  to_skill: string | null;
  kind: "continuation" | "exit" | "repeat";
  /**
   * the input in plain words
   */
  input: string;
  keys: Keys;
  /**
   * [first, last] clip frame of the FROM action, inclusive
   *
   * @minItems 2
   * @maxItems 2
   */
  window?: number[];
  /**
   * fires when the from action ends
   */
  end?: true;
  commands?: {
    skill?: number[];
    quickslot?: number[];
    quickslot_skill?: number[];
    quickslot_current?: number[];
    not_quickslot_skill?: number[];
  };
  conditions: Condition[];
  assumed: Assumed[];
  /**
   * for an edge into a skill PRESS (`to` = SKILL_<n>): the action that press plays
   */
  plays?: string;
}
export interface Keys {
  held?: Key[];
  press?: Key[];
  double?: Key[];
  released?: Key[];
}
/**
 * A resource / gear / class test the best-case profile assumed met (full resources, gear worn, content on).
 */
export interface Assumed {
  name: string;
  args: number[];
  text: string;
}
export interface VariableSet {
  f: number;
  var: string;
  op: string;
  value: number;
  never?: true;
  if?: Condition[][];
}
/**
 * A melee hit area (game data). Attacker at the origin facing forward; world units (100 per metre, inferred). plus_body: the game adds the attacker's scale and body radius to `radius`.
 */
export interface Area {
  kind: "sector" | "box";
  mode: number;
  max_targets: number;
  height_up: number;
  height_down: number;
  height_test: boolean;
  centre_forward: number;
  radius: number;
  /**
   * sector: the ring's inner radius
   */
  inner?: number;
  /**
   * sector: degrees; 180 = full circle
   */
  half_angle?: number;
  /**
   * box
   */
  width?: number;
  /**
   * box
   */
  height?: number;
  /**
   * box
   */
  length?: number;
  plus_body: boolean;
  /**
   * degrees
   */
  angle_offset: number;
}
/**
 * What one damage line of a skill deals. pct is present only for lines the line rule settles (rule single or agree); otherwise null with a reason, for an editor. Never 0.
 */
export interface DamageLine {
  skill: number;
  line: number;
  skill_name: string | null;
  rule: "single" | "agree" | "distinct" | "cooldown" | "hidden" | "summon";
  pct: number | null;
  reason: "distinct" | "cooldown" | "hidden" | "summon" | null;
  reason_text: string | null;
  /**
   * the effect script's x N for each term carrying this % (shipped data; empty when hidden)
   */
  script_hits: (number | null)[];
  /**
   * the effect script's max repeats for each term carrying this % (null = none)
   */
  script_max: (number | null)[];
  /**
   * the line's value as a whole: never stronger than its line mapping
   */
  grade: "inferred" | "needs value";
  value_source: {
    file: string;
    field: string;
    grade: PublicGrade;
  };
  mapping_grade: PublicGrade;
  note?: string;
}
/**
 * One cast of one skill reaching a set of damage groups by the path that lands the final hit earliest (ADR 0004 items 2-5). Its time at any speeds = the action clock summed over `segments`.
 */
export interface Preset {
  skill: string;
  /**
   * <skill>(:<entry action>|@<loop root action>)[~cooldown]|<group>+<group>...; one preset per skill, ENTRY action and group set (the main cast keys its first action, a loop variant its root); a group is <action>[i-j], the 1-based ordinals of its ticks in the action
   */
  key: string;
  name: string | null;
  entry: {
    keys?: Key[];
    not_keys?: Key[];
    /**
     * the entry keys that must stay down after the entry (press vs hold)
     */
    hold?: Key[];
  };
  loop_variant: boolean;
  /**
   * a loop variant's root action
   */
  variant: string | null;
  /**
   * pressed on cooldown, or plays an on-cooldown action (the best-case profile is off cooldown)
   */
  on_cooldown: boolean;
  kind: "simple" | "timed" | null;
  groups: {
    action: string;
    name: string | null;
    ticks: PresetTick[];
  }[];
  path: string[];
  choices: Choice[];
  segments: Segment[];
  zero_length: string[];
  final_hit: {
    action?: string;
    f?: number;
  } | null;
  ms_100: number | null;
  /**
   * another path is faster at 150% of one speed (flagged, not re-picked)
   */
  speed_flip: boolean;
  followups: Followup[];
  /**
   * the skill the preset's damage hits name (a `cards` id)
   */
  card: number | null;
  /**
   * how the card was read from the hits: single skill, or the family-majority rule (docs/presets.md, Cards)
   */
  card_rule: string;
  /**
   * <card>(:<entry action>|@<loop root action>)[~cooldown]|<group>+...; unique in a spec file
   */
  card_key: string | null;
  /**
   * 'entry' (pressed on cooldown) or 'plays <action>' (plays an on-cooldown action, however reached); null off cooldown
   */
  on_cooldown_via: string | null;
  /**
   * per spec: the card id the preset is shown under (e.g. Succession: Beak Kick for Absolute: Beak Kick's hits), or null when the spec does not show it
   */
  specs: {
    succession: number | null;
    awakening: number | null;
  };
  /**
   * per spec: the edges of another kept skill that reach this preset's first action, when its card is shown only because it is reached that way (a superseded Absolute / lower rank, ADR 0004 item 7); else null
   */
  reached_through: {
    succession: null | ReachedVia[];
    awakening: null | ReachedVia[];
  };
  /**
   * the whole preset in a player’s words, one frame-free sentence (docs/presets.md "How it’s played"); null when the player does nothing of their own
   */
  how: string | null;
  /**
   * key into `access_lists`: every way into the preset (item 10)
   */
  access: string;
  /**
   * why the access list is empty, else null
   */
  no_entry: string | null;
  /**
   * the cast’s first action: the preset is the fastest path for its group set FROM this action
   */
  entry_action: string;
  /**
   * entered through a route-only Ultimate (its command opens this route into the base card)
   */
  ultimate: null | {
    id: number;
    name: string | null;
  };
  /**
   * buff (ids only; buff.dbss not parsed) and class-resource requirements of the entry (shared by every entering condset) and of each choice
   */
  requirements: {
    kind: "buff" | "class_resource";
    buff?: number;
    active?: boolean;
    op?: string;
    value?: number;
    where: string;
  }[];
  /**
   * what separates this entry from the other presets of its card with the same visible entry keys (empty when none share them)
   */
  distinguishing: string[];
  /**
   * reached only by a hotbar press of the skill: the keyboard rows take an earlier class-resource branch first
   */
  via_hotbar: boolean;
  /**
   * why the sentence leaves a timing out (empty: every step said)
   */
  how_fallback: string[];
  /**
   * a timed PLAYER action: any choice that is not automatic (a press, release, hold-through, charge, hotbar or skill-command step)
   */
  timed: boolean;
  /**
   * entered through the class's Awakening weapon switch: its command only switches the weapon and hands off into this card (precedence 2, folded; the input stays on the entry)
   */
  weapon_switch: null | {
    id: number;
    name: string | null;
  };
}
export interface PresetTick {
  f: number;
  skill: number;
  /**
   * damage line id (its % is damage_lines[line].pct); null when the hit names no line (`line_reason`)
   */
  line: string | null;
  lines: string[];
  conditional: boolean;
  /**
   * why `line` is null: the hit event names no damage line
   */
  line_reason?: string;
}
/**
 * One decision on the preset path: leave `from` for `to` on `input`; `moment` says what decides when, `how` says it in a player’s words.
 */
export interface Choice {
  from: string;
  to: string;
  input: Input;
  keys: Key[];
  released: Key[];
  moment: Moment;
  /**
   * this choice alone in a player’s words, frame-free
   */
  how: string;
  f: number;
}
/**
 * An input as structure (user, 2026-10-05): keys held / pressed / double-tapped, keys that must be up (`released`, hidden by default: `hide`), the skill command(s) by name, the hotbar, the window and End, `requires` and `assumed` in plain words, a one-line `text`; the condition text only in `raw`. 0.5.5: each command’s `keys` (the key combos that enter its skill, split into `held` / `press`; inferred), `quickslot_skills` (the skill a hotbar hop uses).
 */
export interface Input {
  held: string[];
  press: string[];
  double: string[];
  released: string[];
  hide: string[];
  commands: {
    id: number;
    name: string | null;
    /**
     * the key combos entering the skill (its chain entries): `press` edge keys, `held` level keys — inferred
     */
    keys: {
      held: string[];
      press: string[];
    }[];
  }[];
  quickslot: boolean;
  window: null | number[];
  end: boolean;
  requires: string[];
  assumed: string[];
  text: string;
  raw: string | null;
  quickslot_skills: {
    id: number;
    name: string | null;
  }[];
}
/**
 * What decides the frame a choice leaves its action at (item 3): at_once (the first frame), after_hit (right after hit `hit_index` of `of_hits`), window_open (a window opens at f; `after_branch`: an earlier branch on the same input owns the frames before; `window_of`: the window is another branch into the same action), action_end (the action plays to its end; `charge`: a charge held through; `flows`: the clip flows into its next part), release (held keys let go; `when` is the moment it lands). `f` is the clip frame of the action the choice leaves.
 */
export interface Moment {
  kind: "at_once" | "after_hit" | "window_open" | "action_end" | "release";
  when?: "at_once" | "after_hit" | "window_open" | "action_end";
  f: number;
  hit_index?: number;
  of_hits?: number;
  /**
   * @minItems 2
   * @maxItems 2
   */
  skips_hits?: number[];
  after_branch?: boolean;
  window_of?: {
    input: string;
    held: Key[];
  };
  charge?: boolean;
  flows?: boolean;
  released?: Key[];
  /**
   * the hop fires on a target in range (the best-case profile assumes one)
   */
  target?: boolean;
  /**
   * with `charge`: the held keys whose release fires a continuation (what the player holds through the charge)
   */
  charge_keys?: Key[];
}
/**
 * A skill the cast can go into at or after the preset's final hit (ADR 0004 item 5): the time from entering the preset's first action to entering `to`.
 */
export interface Followup {
  /**
   * plain label: the card(s) it enters, the skill, or "any skill on the hotbar"
   */
  group: string | null;
  skill: string | null;
  to: string | null;
  input: Input;
  /**
   * the action the follow-up leaves from
   */
  at: string | null;
  /**
   * the frame of `at` it opens at
   */
  f: number | null;
  /**
   * key into `segment_lists`
   */
  segments: string;
  ms_100: number | null;
  /**
   * for a follow-up into a skill PRESS (`to` = SKILL_<n>): the action that press plays
   */
  plays?: string;
  /**
   * the card(s) the follow-up enters: the first damage of the action it enters, read by the card rule; several when its branches deal several (a `cards` id each)
   */
  cards: number[];
  /**
   * why `cards` is empty ('no damage card: ...'), else null
   */
  no_card: string | null;
  /**
   * the clip frame of `at` the exit itself opens at (before clamping to the final hit)
   */
  opens_f: number | null;
  /**
   * the exit opens before the final hit (the page’s "true cancel" tag)
   */
  true_cancel: boolean;
  cancel: null | Cancel;
  /**
   * any skill on the hotbar (a quickslot / console-slot press): one per preset or timeline, the earliest; no card
   */
  hotbar?: true;
  /**
   * where in its action the hotbar row opens
   */
  opens?: "at start" | "mid-action" | "at End";
  grade?: PublicGrade;
  /**
   * the engine row (group) the exit is on — not for display
   */
  raw_row: string | null;
  /**
   * entered through a route-only Ultimate (its command opens this route into the base card)
   */
  ultimate: null | {
    id: number;
    name: string | null;
  };
}
/**
 * A true cancel (item 5): the follow-up’s exit opens on the final action before the final hit. Leaving at `f` of `at` (ms_100 from the cast start; `segments` a `segment_lists` key) loses `lost_ticks` (export tick ids), hits `first_lost`..`of_ticks`; `lost_pct` is the confident % they carry, else null with the reason.
 */
export interface Cancel {
  at: string;
  f: number;
  segments: string;
  ms_100: number | null;
  lost_ticks: string[];
  first_lost: number;
  of_ticks: number;
  lost_pct: number | null;
  lost_pct_reason: string | null;
  text: string;
}
export interface ReachedVia {
  from_skill: string;
  from_action: string;
  to_action: string;
  input: string;
  opens_f: number | string | null;
  via?: string | null;
  plays?: string | null;
}
export interface Counts {
  [k: string]: number;
}
/**
 * {reason: {count, names: {name: n}}} — what the exporter left out, by reason and by name.
 */
export interface Dropped {
  [k: string]: {
    count: number;
    names: {
      [k: string]: number;
    };
  };
}
/**
 * A skill as the site shows it: the game skill id the presets' damage hits name, its tree facts, and per spec whether (and as which skill) it is shown.
 */
export interface Card {
  id: number;
  name: string | null;
  param: "normal" | "awaken" | "succession" | null;
  family_root: number | null;
  rank: number | null;
  max_rank: number | null;
  kind: "skill" | "black_spirit" | "no_damage" | "summon";
  /**
   * a Black Spirit skill's bases
   */
  bs_of?: number[];
  /**
   * the skill's alternate version (a `Succession: X` skill when succession-type)
   */
  version?: number;
  /**
   * the skills (`skills` keys) whose input reaches the card's presets
   */
  graph_skills: string[];
  presets: number;
  specs: {
    succession:
      | {
          as: number;
          as_name: string | null;
          reached_through?: ReachedVia[];
        }
      | {
          reason: string;
        };
    awakening:
      | {
          as: number;
          as_name: string | null;
          reached_through?: ReachedVia[];
        }
      | {
          reason: string;
        };
  };
  /**
   * How a value is known, in public words. game data: read from the shipped files (or a census over them). measured: observed in game. inferred: a rule consistent with the data, not read directly. needs value: not known; an editor fills it.
   */
  links_grade: "game data" | "measured" | "inferred" | "needs value";
  /**
   * a Black Spirit card: how it is entered on the file's spec(s) — by its own skill's command, or played by a base skill's press under the Black Spirit gate
   */
  entered_by?: {
    mechanism: "own skill" | "base press";
    action: string;
    from_action: string | null;
    /**
     * the base skill the gate names (IsUseableBlackSpritSkillNo)
     */
    base_card: number | null;
    input: string;
    conditions: Condition[];
    /**
     * the assumed tests in words; the Black Spirit gauge (CombineWavePoint) is assumed full
     */
    gate: string[];
  }[];
  /**
   * key into `access_lists` (item 10)
   */
  access: string;
  /**
   * a no_damage card: one per way it is pressed
   */
  timelines?: Timeline[];
  no_damage_reason?: string;
  /**
   * a summon card: its damage lands through a summon and is not counted yet ("needs value"); `lines` are `damage_lines` ids with a null %
   */
  damage_gap?: {
    text: string;
    lines: string[];
    message: {
      action: string;
      f: number;
      name: string | null;
      keys: number[];
    };
  };
}
/**
 * One press of a no-damage skill: its default path with nothing extra pressed, its segments (the cast), its exits from the cast start and `free_to_act` (the earliest exit into a skill).
 */
export interface Timeline {
  graph_skill: string;
  entry: {
    keys: Key[];
    not_keys: Key[];
    input: Input;
    request?: string;
  };
  path: string[];
  segments: Segment[];
  ms_100: number | null;
  ends: string;
  choices: {
    from: string;
    to: string;
    input: Input;
    f: number;
  }[];
  exits: Exit[];
  free_to_act: null | {
    ms_100: number;
    group: string | null;
    skill: string;
    to: string;
    at: string;
    f: number;
    /**
     * key into `segment_lists`
     */
    segments: string;
  };
  free_to_act_reason: string | null;
}
/**
 * An exit of a no-damage card’s timeline, measured from the CAST START at the earliest frame it opens
 */
export interface Exit {
  /**
   * plain label: the card(s) it enters, the skill, or "any skill on the hotbar"
   */
  group: string | null;
  skill: string | null;
  to: string | null;
  input: Input;
  /**
   * the action the follow-up leaves from
   */
  at: string | null;
  /**
   * the frame of `at` it opens at
   */
  f: number | null;
  /**
   * key into `segment_lists`
   */
  segments: string;
  ms_100: number | null;
  /**
   * for a follow-up into a skill PRESS (`to` = SKILL_<n>): the action that press plays
   */
  plays?: string;
  /**
   * the card(s) the follow-up enters: the first damage of the action it enters, read by the card rule; several when its branches deal several (a `cards` id each)
   */
  cards: number[];
  /**
   * why `cards` is empty ('no damage card: ...'), else null
   */
  no_card: string | null;
  /**
   * any skill on the hotbar (a quickslot / console-slot press): one per preset or timeline, the earliest; no card
   */
  hotbar?: true;
  /**
   * where in its action the hotbar row opens
   */
  opens?: "at start" | "mid-action" | "at End";
  grade?: PublicGrade;
  /**
   * the engine row (group) the exit is on — not for display
   */
  raw_row: string | null;
}
/**
 * One way into a preset or card (item 10): press (the skill’s own input from idle), skill_request (entered by a skill press SKILL_<n>), loop (from an earlier action of the same cast), other_skill / own_skill (a follow-up of an exported preset entering it). A follow-up entry names the preset and the index of its follow-up (which carries the action, frame, input and time). 0.5.1: press = FROM IDLE (an idle row enters it, `idle` the evidence); command = an entry outside the charts; from_skill = the actions entering it, per source skill (own = the preset’s skill, its loop included; all = every action of that skill).
 */
export interface AccessEntry {
  kind: "press" | "command" | "skill_request" | "loop" | "other_skill" | "own_skill" | "from_skill" | "hotbar";
  input?: Input;
  keys?: Key[];
  not_keys?: Key[];
  request?: string;
  skill_no?: number;
  from_action?: string;
  from_preset?: string;
  from_card?: number | null;
  f?: number | null;
  action?: string;
  /**
   * index into the from_preset’s followups
   */
  followup?: number;
  /**
   * press: the idle rows that enter the action (evidence)
   */
  idle?: {
    action: string;
    raw_row: string;
    input: Input;
  }[];
  card?: number | null;
  name?: string | null;
  own?: boolean;
  actions?: string[];
  /**
   * every action of that skill the file exports enters it
   */
  all?: boolean;
  of?: number;
  /**
   * entered through a route-only Ultimate (its command opens this route into the base card)
   */
  ultimate?: null | {
    id: number;
    name: string | null;
  };
  skills?: string[];
  /**
   * from_skill: per entering action, the routes it enters by (a route-only Ultimate’s command, plainly, or both)
   */
  routes?: {
    [k: string]: ("plain" | "ultimate")[];
  };
  /**
   * press: the entry's command is the class's Awakening weapon switch, folded into this card (the input it adds)
   */
  weapon_switch?: null | {
    id: number;
    name: string | null;
  };
}
export interface Manifest {
  schema: "0.5.6";
  build: string;
  files: {
    [k: string]: {
      class: string;
      spec: Spec | null;
      sha256: string;
      bytes: number;
      counts: Counts;
      dropped: {
        [k: string]: number;
      };
      presets_status: string;
      damage_source: string;
      spec_scope: {
        [k: string]: string;
      };
      /**
       * whether the presets had the skill families (skilltype.dbss) their cast-end rule needs: 'ok', 'unavailable: <reason>', or 'not generated'. export_check fails unless 'ok'.
       */
      presets_family_roots: string;
    };
  };
  dropped_total: {
    [k: string]: number;
  };
}
export interface Golden {
  schema: "0.5.6";
  build: string;
  speed_sets: {
    [k: string]: Speeds;
  };
  files: {
    [k: string]: {
      clock: GoldenClock[];
      /**
       * [preset key, speed set name, ms]: the clock summed over the preset's segments
       */
      presets: [string, string, number | null][];
    };
  };
}
