// Generates lib/export-types.ts from the export schema in data/schema/.
import { compile } from 'json-schema-to-typescript';
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

const dir = 'data/schema';
const file = readdirSync(dir).filter((f) => /^export-[\d.]+\.json$/.test(f)).sort().pop();
if (!file) throw new Error(`no export-<version>.json in ${dir}`);
const schema = JSON.parse(readFileSync(join(dir, file), 'utf8'));
const ts = await compile(schema, 'BdoExport', {
  bannerComment: `/* Generated by \`npm run types\` from data/schema/${file}. Do not edit. */`,
  unreachableDefinitions: true,
  additionalProperties: false,
  strictIndexSignatures: false,
  format: true,
  // min/max tuples nested in arrays come out without parentheses
  ignoreMinAndMaxItems: true,
  cwd: dir,
});
writeFileSync('lib/export-types.ts', ts);
console.log(`lib/export-types.ts from ${file} (${ts.length} chars)`);
